### PR TITLE
Adds some altitude shortcuts

### PR DESCRIPTION
**Pull request by Lugghawk**
Adds some altitude shortcuts for 400, 1200, 1500, 2000ft

Here's a streamable of it in action. 

https://streamable.com/aqlpvb

### CODE REVIEW

**Comment by Quantx** [comment]
I like it. But those values migth be a bit small since I increased the height limit to 20,000. What are you the thoughts on having a +1000 -1000 button instead?

**Comment by lordfiSh** [comment]
Very nice addition, its quite annoying to change the altitude at every waypoint. 
I didn't know that you can fly till 20,000 meters, but is this even useful? AA Range is 1200 meters (?), Camera can only spot at ~5 km and bombs wont hit at that high altitude cause of wind. I think that suggestion values are ok.

**Comment by Lugghawk** [comment]
> I like it. But those values migth be a bit small since I increased the height limit to 20,000. What are you the thoughts on having a +1000 -1000 button instead?
> 
> You could set the default increments to be 10 with buttons for 100 and 1000. Kind of like how you request a quantity of items on the barge screen.

Yeah the values were picked based on what worked for me. I also didn't want to break out of the limits posed by the vanilla game, a personal choice since not everyone uses the enhancer. If you decide to keep it that way, I'm not sure an increment would be more useful than the default altitude buttons which provide altitude adjustments in increments of 50ft, so fine adjustments could be made there. 

Let me know what you think.

**Comment by Lugghawk** [comment]
Also a -1000/+1000 series of buttons could be on a new row if you definitely want increments.

**Comment by Quantx** [comment]
The reason the limit was set to 20000 was so that you could fly over the carrier's radar distance of 10,000.

**Comment by Lugghawk** [comment]
@Quantx What changes would you like to see? 

The values work fine for me, but my experience in CC2 is limited. We can add more values, but they start getting cramped: 
image

Another row is possible too.

**Comment by Guardian3k** [comment]
Hello bros, i can see all the fine stuff you making. Concerning alt change, would it be possible instead of having alt defined just to have bigger increments buttons? lets say buttons like (-1000,-500,-200, +200, +500, +1000). ? btw. is it possible for a game to detect if a player is holding shift button while he is clicking on the screen?

**Comment by cfiorille** [comment]
How about something like this?

- 100 is used for straight in approaches to the carrier so your birds don't enter the pattern.
- 400 is standard alt (Should we change this  to 500m to match the increment buttons?)
- 1.5k and 2k are standard alts I have seen used in Multi-player
- 4k for those that like to be outside the missle detect range of the Swordfishes (might need to be +6k... depends on who you ask) 😄

**Comment by Lugghawk** [comment]
> How about something like this?
> 
>     * 100 is used for straight in approaches to the carrier so your birds don't enter the pattern.
> 
>     * 400 is standard alt (Should we change this  to 500m to match the increment buttons?)
> 
>     * 1.5k and 2k are standard alts I have seen used in Multi-player
> 
>     * 4k for those that like to be outside the missle detect range of the Swordfishes (might need to be +6k... depends on who you ask) 😄
> 
> 
> 

Seems like a pretty good compromise to me.

**Comment by Guardian3k** [comment]
> How about something like this?
> 
> * 100 is used for straight in approaches to the carrier so your birds don't enter the pattern.
> * 400 is standard alt (Should we change this  to 500m to match the increment buttons?)
> * 1.5k and 2k are standard alts I have seen used in Multi-player
> * 4k for those that like to be outside the missle detect range of the Swordfishes (might need to be +6k... depends on who you ask) 😄
> 
> 

this is amazing

**Comment by Quantx** [comment]
That works great! Im going to set the increments to be 100, and 1000 with the default increment to be 10. That way you can dial in a precise altitude. Those presets look great too.

**Pull request merged**
